kind: source
spec:
  name: "aws"
  version: "v2.5.1"
  tables: [
    "aws_accessanalyzer_analyzers",
    "aws_cloudformation_stacks",
    "aws_cloudtrail_trails",
    "aws_cloudwatch_alarms",
    "aws_cloudwatchlogs_log_groups",
    "aws_cloudwatchlogs_metric_filters",
    "aws_config_configuration_recorders",
    "aws_config_conformance_packs",
    "aws_ec2_byoip_cidrs",
    "aws_ec2_customer_gateways",
    "aws_ec2_ebs_snapshots",
    "aws_ec2_ebs_volumes",
    "aws_ec2_egress_only_internet_gateways",
    "aws_ec2_eips",
    "aws_ec2_flow_logs",
    "aws_ec2_hosts",
    "aws_ec2_images",
    "aws_ec2_instances",
    "aws_ec2_internet_gateways",
    "aws_ec2_key_pairs",
    "aws_ec2_nat_gateways",
    "aws_ec2_network_acls",
    "aws_ec2_network_interfaces",
    "aws_ec2_regional_config",
    "aws_regions",
    "aws_ec2_route_tables",
    "aws_ec2_security_groups",
    "aws_ec2_subnets",
    "aws_ec2_transit_gateways",
    "aws_ec2_vpc_endpoint_service_configurations",
    "aws_ec2_vpc_endpoints",
    "aws_ec2_vpc_peering_connections",
    "aws_ec2_vpcs",
    "aws_ec2_vpn_gateways",
    "aws_ecr_repositories",
    "aws_ecs_clusters",
    "aws_ecs_task_definitions",
    "aws_efs_filesystems",
    "aws_eks_clusters",
    "aws_firehose_delivery_streams",
    "aws_guardduty_detectors",
    "aws_iam_accounts",
    "aws_iam_credential_reports",
    "aws_iam_groups",
    "aws_iam_openid_connect_identity_providers",
    "aws_iam_password_policies",
    "aws_iam_policies",
    "aws_iam_roles",
    "aws_iam_saml_identity_providers",
    "aws_iam_server_certificates",
    "aws_iam_users",
    "aws_iam_virtual_mfa_devices",
    "aws_inspector_findings",
    "aws_inspector2_findings",
    "aws_kms_keys",
    "aws_lambda_functions",
    "aws_lambda_layers",
    "aws_lambda_runtimes",
    "aws_organizations_accounts",
    "aws_rds_certificates",
    "aws_rds_cluster_parameter_groups",
    "aws_rds_cluster_snapshots",
    "aws_rds_clusters",
    "aws_rds_db_parameter_groups",
    "aws_rds_db_security_groups",
    "aws_rds_db_snapshots",
    "aws_rds_event_subscriptions",
    "aws_rds_instances",
    "aws_rds_subnet_groups",
    "aws_resourcegroups_resource_groups",
    "aws_route53_delegation_sets",
    "aws_route53_domains",
    "aws_route53_health_checks",
    "aws_route53_hosted_zones",
    "aws_route53_traffic_policies",
    "aws_s3_accounts",
    "aws_s3_buckets",
    "aws_secretsmanager_secrets",
    "aws_ses_templates",
    "aws_shield_attacks",
    "aws_shield_protection_groups",
    "aws_shield_protections",
    "aws_shield_subscriptions",
    "aws_sns_subscriptions",
    "aws_sns_topics",
    "aws_sqs_queues",
    "aws_ssm_documents",
    "aws_ssm_instances",
    "aws_ssm_parameters",
    "aws_workspaces_directories",
    "aws_workspaces_workspaces"
  ]
  destinations: ["postgresql"]
  spec:
    regions: ["us-east-1","us-east-2"]
