kind: destination
spec:
  name: "postgresql"
  version: "v1.0.0"
  write_mode: "overwrite" # overwrite, overwrite-delete-stale, append
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/postgres?sslmode=disable"
